version = 0.1
[default.deploy.parameters]
stack_name = "<your-stack-name>"
resolve_s3 = true
s3_prefix = "<your-s3-prefix>"
region = "<your-region>"
capabilities = "CAPABILITY_IAM"
image_repositories = [] 